# [Ultimate Smart Home Media Server with Docker and Ubuntu][1]
#
# [1]: https://www.smarthomebeginner.com/docker-home-media-server-2018-basic/
version: "3.6"
volumes:
    media:
        driver: local
        driver_opts:
            type: nfs
            o: addr=192.168.0.103,rw,nordirplus
            device: ":/mnt/array1/media"
services:
    plex:
        image: lscr.io/linuxserver/plex:latest
        container_name: plex
        network_mode: host
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - VERSION=docker
        volumes:
            - ./config/plex:/config
            - media:/media
        devices:
            - "/dev/dri:/dev/dri"
        restart: unless-stopped
    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        restart: always
        command: -H unix:///var/run/docker.sock
        ports:
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./config/portainer/data:/data
            - ./config/shared:/shared
        environment:
            - TZ=${TZ}
    organizr:
        container_name: organizr
        restart: always
        image: organizr/organizr:latest
        volumes:
            - ./config/organizr:/config
            - ./config/shared:/shared
        ports:
            - "8080:80"
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - fmp="false"
    watchtower:
        container_name: watchtower
        restart: always
        image: containrrr/watchtower:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --schedule "0 0 4 * * *" --cleanup
    transmission:
        container_name: transmission-vpn
        image: haugene/transmission-openvpn:latest
        cap_add:
            - NET_ADMIN
        devices:
            - "/dev/net/tun"
        restart: always
        ports:
            - "9091:9091"
        dns:
            - 1.1.1.1
            - 1.0.0.1
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./config/transmission-vpn/config:/config
            - ./config/transmission-vpn/data:/data
            - ./config/shared:/shared
            - media:/media
        logging:
            driver: "json-file"
            options:
                max-size: "500k"
                max-file: "10"
        secrets:
            - openvpn_creds
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings --mssfix 1460
            - PIA_OPENVPN_CONFIG_BUNDLE=openvpn
            - OPENVPN_CONFIG=ca_toronto
            - LOCAL_NETWORK=192.168.0.0/24
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - TRANSMISSION_DOWNLOAD_DIR=/media/torrents/completed
            - TRANSMISSION_INCOMPLETE_DIR=/media/torrents/incomplete
            - TRANSMISSION_WATCH_DIR=/media/torrents/watch
            - TRANSMISSION_UMASK=002
            - TRANSMISSION_WEB_UI=combustion
    radarr:
        image: linuxserver/radarr
        container_name: radarr
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./config/radarr:/config
            - ./config/shared:/shared
            - media:/media
        ports:
            - "7878:7878"
        restart: always
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./config/sonarr:/config
            - ./config/shared:/shared
            - media:/media
        ports:
            - "8989:8989"
        restart: always
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
    bazarr:
        image: linuxserver/bazarr
        container_name: bazarr
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./config/bazarr:/config
            - ./config/shared:/shared
            - media:/media
        ports:
            - "6767:6767"
        restart: always
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
    prowlarr:
        image: lscr.io/linuxserver/prowlarr:develop
        container_name: prowlarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ./config/prowlarr:/config
        ports:
            - 9696:9696
        restart: unless-stopped
    ombi:
        image: linuxserver/ombi
        container_name: ombi
        volumes:
            - ./config/ombi:/config
            - ./config/shared:/shared
        ports:
            - "3579:3579"
        restart: always
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        hostname: shepard
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "8081:80/tcp"
        # Never auto-update pihole to avoid network disruptions
        # See https://github.com/pi-hole/docker-pi-hole/#note-on-watchtower
        #     https://containrrr.dev/watchtower/container-selection/#full_exclude
        labels:
            - "com.centurylinklabs.watchtower.enable=false"
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - WEBPASSWORD_FILE=/run/secrets/pihole_webpassword
            - FTLCONF_LOCAL_IPV4=192.168.0.130
            - DNS1=1.1.1.1
            - DNS2=1.0.0.1
        # Must add --dns arg, otherwise pi-hole fails to start with
        # "DNS resolution is currently unavailable" message in the logs.
        # See https://github.com/pi-hole/docker-pi-hole/issues/342
        dns:
            - 127.0.0.1
            - 1.1.1.1
        volumes:
            - ./config/pihole/pihole:/etc/pihole
            - ./config/pihole/dnsmasq.d:/etc/pihole/dnsmasq.d
        secrets:
            - pihole_webpassword
        restart: unless-stopped
    swag:
        image: ghcr.io/linuxserver/swag
        container_name: swag
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - URL=bshelley.duckdns.org
            - SUBDOMAINS=wildcard
            - VALIDATION=duckdns
            - FILE__DUCKDNSTOKEN=/run/secrets/duckdns_token
        volumes:
            - ./config/swag:/config
        ports:
            - 443:443
            - 80:80
        secrets:
            - duckdns_token
        restart: unless-stopped
    duckdns:
        image: ghcr.io/linuxserver/duckdns
        container_name: duckdns
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - SUBDOMAINS=bshelley,bensflix,benshelley
            - FILE__TOKEN=/run/secrets/duckdns_token
        secrets:
            - duckdns_token
        volumes:
            - ./config/duckdns:/config
        restart: unless-stopped

secrets:
    duckdns_token:
        file: ./config/secrets/duckdns_token
    openvpn_creds:
        file: ./config/secrets/openvpn_creds
    pihole_webpassword:
        file: ./config/secrets/pihole_webpassword

