# [Ultimate Smart Home Media Server with Docker and Ubuntu][1]
#
# [1]: https://www.smarthomebeginner.com/docker-home-media-server-2018-basic/
version: "3.6"
volumes:
    media:
        driver: local
        driver_opts:
            type: nfs
            o: addr=192.168.7.37,rw,nordirplus
            device: ":/mnt/array1/media"
services:
    portainer:
        image: portainer/portainer
        container_name: portainer
        restart: always
        command: -H unix:///var/run/docker.sock
        ports:
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${USERDIR}/docker/portainer/data:/data
            - ${USERDIR}/docker/shared:/shared
        environment:
            - TZ=${TZ}
    organizr:
        container_name: organizr
        restart: always
        image: linuxserver/organizr
        volumes:
            - ${USERDIR}/docker/organizr:/config
            - ${USERDIR}/docker/shared:/shared
        ports:
            - "9983:80"
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
    watchtower:
        container_name: watchtower
        restart: always
        image: containrrr/watchtower:armhf-latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --schedule "0 0 4 * * *" --cleanup
    transmission:
        image: haugene/transmission-openvpn:latest-armhf
        cap_add:
            - NET_ADMIN
        devices:
            - "/dev/net/tun"
        restart: always
        ports:
            - "9091:9091"
        dns:
            - 1.1.1.1
            - 1.0.0.1
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${USERDIR}/docker/transmission-vpn:/data
            - ${USERDIR}/docker/shared:/shared
            - ${USERDIR}/torrents/watch:/data/watch
            - ${USERDIR}/torrents/completed:/data/completed
            - ${USERDIR}/torrents/incomplete:/data/incomplete
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_USERNAME=p7356348
            - OPENVPN_PASSWORD=OWmg4VvyZnk1
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - OPENVPN_CONFIG=CA Vancouver
            - LOCAL_NETWORK=192.168.7.0/24
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
            - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.7.*"
            - TRANSMISSION_RPC_PASSWORD=benflix
            - TRANSMISSION_RPC_USERNAME=benflix
            - TRANSMISSION_UMASK=002
            - TRANSMISSION_RATIO_LIMIT=1.00
            - TRANSMISSION_RATIO_LIMIT_ENABLED=true
    radarr:
        image: linuxserver/radarr
        container_name: radarr
        volumes:
            - ${USERDIR}/docker/radarr:/config
            - ${USERDIR}/torrents/completed:/downloads
            - media:/media
            - /etc/localtime:/etc/localtime:ro
            - ${USERDIR}/docker/shared:/shared
        ports:
            - "7878:7878"
        restart: always
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        volumes:
            - ${USERDIR}/docker/sonarr:/config
            - ${USERDIR}/torrents/completed:/downloads
            - media:/media
            - /etc/localtime:/etc/localtime:ro
            - ${USERDIR}/docker/shared:/shared
        ports:
            - "8989:8989"
        restart: always
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
    jackett:
        image: linuxserver/jackett
        container_name: jackett
        volumes:
            - ${USERDIR}/docker/jackett:/config
            - ${USERDIR}/torrents/completed:/downloads
            - /etc/localtime:/etc/localtime:ro
            - ${USERDIR}/docker/shared:/shared
        ports:
            - "9117:9117"
        restart: always
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
    ombi:
        image: linuxserver/ombi
        container_name: ombi
        volumes:
            - ${USERDIR}/docker/ombi:/config
            - ${USERDIR}/docker/shared:/shared
        ports:
            - "3579:3579"
        restart: always
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}



